/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_uXUPZBvzJ',
  aws_user_pools_web_client_id: '2e3a3h5d3pvshlnse5u48ml57a',
};

export default awsmobile;
